name: 'Typhon'
inputs:
  project_name:
    required: true
    default: ${{ github.repository }}
  project_url:
    required: true
    default: "github:${{ github.repository }}"
  jobset_name:
    required: true
    default: ${{ github.ref_name }}
  jobset_url:
    required: true
    default: "github:${{ github.repository }}/${{ github.sha }}"
  key:
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - run: |
        nix shell \
          nixpkgs#age \
          nixpkgs#bubblewrap \
          nixpkgs#jo \
          nixpkgs#jq \
          --command action.sh
      shell: bash
      env:
        PROJECT_NAME: ${{ inputs.project_name }}
        PROJECT_URL: ${{ inputs.project_url }}
        JOBSET_NAME: ${{ inputs.jobset_name }}
        JOBSET_URL: ${{ inputs.jobset_url }}
        KEY: ${{ inputs.key }}
